DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(90) NOT NULL,
    first_name VARCHAR(90) DEFAULT NULL,
    last_name VARCHAR(90) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT Now() NOT NULL,
    updated_at TIMESTAMP DEFAULT Now() NOT NULL
);
DROP TABLE IF EXISTS posts;
CREATE TABLE posts
(
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(180) DEFAULT NULL,
    url VARCHAR(510) DEFAULT NULL,
    content TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT Now() NOT NULL,
    updated_at TIMESTAMP DEFAULT Now() NOT NULL,
    user_id INTEGER
);
DROP TABLE IF EXISTS comments;
CREATE TABLE comments
(
    id SERIAL PRIMARY KEY NOT NULL,
    body VARCHAR(510) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT Now() NOT NULL,
    updated_at TIMESTAMP DEFAULT Now() NOT NULL,
    user_id INTEGER,
    post_id INTEGER
);
